[package]
name = "ads_auction"
version = "0.1.0"
description = "ClaimSpot peer-to-peer sponsorship auction program"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "ads_auction"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = "=1.0.2"
anchor-spl = "=1.0.2"
ephemeral-rollups-sdk = { version = "=0.17.0", features = ["anchor"] }
session-keys = { version = "=3.1.1", features = ["no-entrypoint"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
