[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
basic = "CkKbXccct8gWcfUyZzv2UGbDLtGSoMcsM6ZrWQ5dPnvZ"

[programs.devnet]
basic = "CkKbXccct8gWcfUyZzv2UGbDLtGSoMcsM6ZrWQ5dPnvZ"

[provider]
cluster = "devnet"
wallet = ".keys/devnet-deployer.json"

[scripts]
test = "../node_modules/.bin/tsx --test tests/basic.test.ts"
